version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: random-ia-test
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    # networks:
    #   - raven-db-poc
#   db:
#     image: ravendb/ravendb
#     container_name: raven-db
#     ports:
#       - '8080:8080'
#       - '38888:38888'
#     environment:
#       - UNSECURED_ACCESS_ALLOWED=PublicNetwork
#       - PUBLIC_SERVER_URL=http://localhost:8080
#     networks:
#       - raven-db-poc

# networks:
#   raven-db-poc:
#     driver: bridge
